#!/usr/bin/env ruby
###############################################################################
##  6502 Assembler for the NES's 2A03
##
##  Usage: ./n65 <infile.asm>
##
##  This file runs the assembler though the commandline frontend.

require_relative 'lib/front_end'

N65::FrontEnd.new(ARGV).run
